<?php
// Check if engagement_id is provided in the URL parameter
if(isset($_GET['engagement_id'])) {
    // Retrieve engagement_id from URL parameter
    $engagement_id = $_GET['engagement_id'];

    // Get the first day of the current month
    $target_start = date('Y-m-01');
    
    // Get the last day of the current month
    $target_end = date('Y-m-t');
	
	 $lead = 1;

    // Data for test creation - Test 1
    $data_test1 = array(
        'id' => 'created', // You can leave it as 'created' if it's automatically generated by DefectDojo
        'test_type' => 1,
        'test_type_name' => 'API Test',
        'title' => 'API Tests',
        'target_start' => $target_start,
        'target_end' => $target_end,
        'lead' => $lead , // Assuming lead is stored in session
        'environment' => 1,
        'engagement' => $engagement_id // Use the engagement_id retrieved from the URL
    );

    // Data for test creation - Test 2
    $data_test2 = array(
        'id' => 'created', // You can leave it as 'created' if it's automatically generated by DefectDojo
        'test_type' => 3,
        'test_type_name' => 'Pen Test',
        'title' => 'Pen Test',
        'target_start' => $target_start,
        'target_end' => $target_end,
        'lead' => $lead, // Assuming lead is stored in session
        'environment' => 1,
        'engagement' => $engagement_id // Use the engagement_id retrieved from the URL
    );

    // Convert data to JSON format
    $payload_test1 = json_encode($data_test1);
    $payload_test2 = json_encode($data_test2);

    // API endpoint URL
    $url = 'https://demo.defectdojo.org/api/v2/tests/';

    // Headers
    $headers = array(
        'Content-Type: application/json',
        'Authorization: Token 856d771a223de97e8b1616bf02f42f004bc7981f' // Replace YOUR_TOKEN_HERE with your actual token
    );

    // Initialize cURL session for Test 1
    $ch1 = curl_init($url);
    // Initialize cURL session for Test 2
    $ch2 = curl_init($url);

    // Set cURL options for Test 1
    curl_setopt($ch1, CURLOPT_CUSTOMREQUEST, 'POST');
    curl_setopt($ch1, CURLOPT_POSTFIELDS, $payload_test1);
    curl_setopt($ch1, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch1, CURLOPT_HTTPHEADER, $headers);

    // Set cURL options for Test 2
    curl_setopt($ch2, CURLOPT_CUSTOMREQUEST, 'POST');
    curl_setopt($ch2, CURLOPT_POSTFIELDS, $payload_test2);
    curl_setopt($ch2, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch2, CURLOPT_HTTPHEADER, $headers);

    // Execute cURL sessions
    $result_test1 = curl_exec($ch1);
    $result_test2 = curl_exec($ch2);

    // Check for errors for Test 1
    if($result_test1 === false) {
        echo 'Error for Test 1: ' . curl_error($ch1);
    } else {
        // Decode the JSON response for Test 1
        $response_test1 = json_decode($result_test1, true);

        // Check if test 1 creation was successful
        if(isset($response_test1['id'])) {
            // Print success message for Test 1
            echo "Test 1 created successfully with ID: {$response_test1['id']}. ";
        } else {
            echo "Error for Test 1: Test creation failed.";
        }
    }

    // Check for errors for Test 2
    if($result_test2 === false) {
        echo 'Error for Test 2: ' . curl_error($ch2);
    } else {
        // Decode the JSON response for Test 2
        $response_test2 = json_decode($result_test2, true);

        // Check if test 2 creation was successful
        if(isset($response_test2['id'])) {
            // Print success message for Test 2
            echo "Test 2 created successfully with ID: {$response_test2['id']}. ";
        } else {
            echo "Error for Test 2: Test creation failed.";
        }
    }

    // Close cURL sessions
    curl_close($ch1);
    curl_close($ch2);

    // Display the Engagement ID
    echo "Engagement ID: $engagement_id, Created successfully.";
} else {
    // If engagement_id is not provided in the URL parameter, display an error message
    echo "Error: Engagement ID not provided in URL.";
}
?>
